name: Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Start MVC App
        run: dotnet run --project 7071Sprint1Demo/7071Sprint1Demo.csproj &
        env:
          ASPNETCORE_URLS: http://localhost:8080

      # - name: Run Selenium Tests
      #   run: dotnet test TestProject/TestProject.csproj --no-build --configuration Release
      #   env:
      #     BASEURL: http://localhost:8080
