name: Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Publish MVC App
        run: dotnet publish 7071Sprint1Demo/7071Sprint1Demo.csproj -c Release -o out

      - name: Start MVC App
        run: |
          nohup dotnet out/7071Sprint1Demo.dll --urls=http://localhost:5000 > log.txt 2>&1 &

      - name: Wait for server to start
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:5000 | grep -q "<html"; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 2
          done

      - name: Run Selenium Tests
        run: dotnet test TestProject/TestProject.csproj --no-build --configuration Release
        env:
          BASEURL: http://localhost:5000
