name: Production Build & Deployment
run-name: ${{ github.actor }} is deploying 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Get latest code
        uses: actions/checkout@v4
      - name: 🚚 Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: 📦 Restore dependencies
        run: dotnet restore
      - name: 🔨 Build .NET
        run: dotnet build --configuration Release --no-restore
